name = "xraycontainers"
main = "src/index.js"
compatibility_date = "2026-03-26"
workers_dev = false


[triggers]
crons = ["*/5 * * * *"]

[limits]
cpu_ms = 300000

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

#智能放置
[placement]
mode = "smart"

[[containers]]
class_name = "XrayContainer"
image = "./Dockerfile"
instance_type = "standard-2"

# max_instances = 20

[containers.constraints]
regions = ["APAC"]

[[durable_objects.bindings]]
name = "XRAY"
class_name = "XrayContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "XrayContainer" ]